### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [Bartosz007/cztery-w-rzedzie#1]
1. Pylint pomoże Panu ujednolicić używanie białych znaków.

2. Nazwa funkcji `ai()` nie jest najszczęśliwsza. *Vide* punkt o skrótach w 2. rozdziale Poradnika.

3. Zawartość pliku `AI.py` prosi się o zrobienie z niej klasy, w której będą sobie w spokoju siedzieć dotychczasowe zmienne globalne (rozdział 2.)

4. Z `"#D15304"`, [5](https://github.com/Bartosz007/cztery-w-rzedzie/blob/ff11b8bbf6ee659e6b40b200bcd5d5e0e9b9c9ac/ConnectFour.py#L32), [41](https://github.com/Bartosz007/cztery-w-rzedzie/blob/ff11b8bbf6ee659e6b40b200bcd5d5e0e9b9c9ac/GameFunctions.py#L178) itp. zrobić nazwane stałe.

**Comment by Bartosz007** [comment]
Poprawiłem wszystkie pliki z pomocą Pylinta - głownie spacje, wcięcia, długości linii, nazwy zmiennych.
Zawartość pliku AI.py przerobiłem na klasę. 
Dodałem również zmienne globalne.
Utworzyłem plik z testami.

**Comment by MarcinCiura** [comment]
Dziękuję za poprawki. Jest już nieźle.

1. Stałe `COLS`, `ROWS` itp. nie powinny się powtarzać po plikach. Najlepiej je wyjąć do osobnego modułku (4. rozdział).
2. [Stała `COLOR`](https://github.com/Bartosz007/cztery-w-rzedzie/blob/3c348726fde926a769d05a6031c2b4dfe6f089c2/okno_gry.py#L18) ma mylącą nazwę. To, że to jest kolor, to wiem i bez nazwy. Nazwa powinna odzwierciedlać zastosowanie.
3. Zysk w [jedynym użycie `partial` w tym module](https://github.com/Bartosz007/cztery-w-rzedzie/blob/3c348726fde926a769d05a6031c2b4dfe6f089c2/okno_gry.py#L5) przez niepisanie przed nim `functools` jest żaden. To samo pozostałe importy (2. rozdział).
4. [Nazwać magiczne stałe](https://github.com/Bartosz007/cztery-w-rzedzie/blob/3c348726fde926a769d05a6031c2b4dfe6f089c2/mechanika_gry.py#L109) (2. rozdział).
5. [Użyć swoich stałych](https://github.com/Bartosz007/cztery-w-rzedzie/blob/3c348726fde926a769d05a6031c2b4dfe6f089c2/mechanika_gry.py#L240).
6. [`+=`, `-=`](https://github.com/Bartosz007/cztery-w-rzedzie/blob/3c348726fde926a769d05a6031c2b4dfe6f089c2/mechanika_gry.py#L247)
7. Wolałbym elastyczniejszą organizację klas: dorobić `GraczLudzki` analogiczny do gracza komputerowego, mający metodę `make_move()`. Z klasy `GameFunctions` pousuwać pola `__player` i `__ai_player` i nie tworzyć gracza komputerowego co chwila nowego. Za to przekazywać do jej konstruktora `first_player` i `second_player` z zewnątrz i używać ich metod `make_move()`. W ten sposób będzie można grać białymi albo czarnymi, albo w dwoje ludzi, albo nawet w dwóch graczy komputerowych, prawda?
8. [Proszę się zdecydować na jeden język w nazwach](https://github.com/Bartosz007/cztery-w-rzedzie/blob/3c348726fde926a769d05a6031c2b4dfe6f089c2/gracz_komputerowy.py#L9).
9. `test_mechanika_gry.py` przemianować na `mechanika_gry_test.py`, `class Tests` na `class TestGameFunctions` i [z tego](https://github.com/Bartosz007/cztery-w-rzedzie/blob/3c348726fde926a769d05a6031c2b4dfe6f089c2/test_mechanika_gry.py#L22) zrobić
```
def setUp(self):
    self.tpoles = ...
```
10. Pańskie testy to prawdziwy skarb: nigdy nie zawodzą. Czy wie Pan, dlaczego? Rozwiązanie zagadki w [tym wierszu](https://github.com/Bartosz007/cztery-w-rzedzie/blob/3c348726fde926a769d05a6031c2b4dfe6f089c2/test_mechanika_gry.py#L98).

**Comment by Bartosz007** [comment]
1. Utworzyłem oddzielny plik na stałe constans.py. Posegregowałem je według przeznaczenia i umieściłem w oddzielnych klasach.
2. Nazwę zmieniłem na BLUE oraz analogicznie na ORANGE
3. Poprawiłem importy. Niestety "import tkinter.messagebox" nie da się usunąć, ponieważ wyrzuca błąd: "AttributeError: module 'tkinter' has no attribute 'messagebox'".
4. Utworzyłem nowe stałe i część z nich zamieściłem w constans.py.
5,6 - Poprawiłem.
7. Utworzyłem oddzielne klasy dla poszczególnych typów graczy. Obliczenia i pilnowanie kolejności graczy znajduje się teraz w metodzie __hit. Metody calculate i ai_calculate usunąłem.
8. Nazwy pozmieniałem na angielskie i bardziej odpowiadające przeznaczeniu.
9,10. Nazwa zmieniona, testy poprawione.

**Comment by MarcinCiura** [comment]
2. `BLUE` i `ORANGE` — rozumiem, że na kolory graczy — to złe nazwy. Kiedy Pan zechce, żeby jeden gracz był zielony, powstanie absurd. *Odzwierciedlać zastosowanie*, nie zawartość.
3. Jest OK. `messagebox` to moduł.

**Comment by MarcinCiura** [comment]
1. [To](https://github.com/Bartosz007/cztery-w-rzedzie/blob/91fcb3779fbba129f1024442cd2b2d4ddeb2f60b/game_mechanics_test.py#L40) miało poznikać.
2. [`from utils import players_utils`](https://github.com/Bartosz007/cztery-w-rzedzie/blob/91fcb3779fbba129f1024442cd2b2d4ddeb2f60b/game_mechanics_test.py#L5). Importy posortować (2. rozdział).
3. [Tu też](https://github.com/Bartosz007/cztery-w-rzedzie/blob/91fcb3779fbba129f1024442cd2b2d4ddeb2f60b/game_mechanics.py#L3) `from ... import ...`.
4. [To](https://github.com/Bartosz007/cztery-w-rzedzie/blob/91fcb3779fbba129f1024442cd2b2d4ddeb2f60b/game_mechanics.py#L91) jest złe. Należy się zapytać obiektu gracza, co wypisać.
5. [Tu](https://github.com/Bartosz007/cztery-w-rzedzie/blob/91fcb3779fbba129f1024442cd2b2d4ddeb2f60b/game_mechanics.py#L134) też. Nadto nie rozumiem tych akrobacji z pierwszym i drugim graczem. Czy nie można wywołać metody `.make_move()`, czy jak ona się nazywa, pierwszego gracza? Wszelkie `isinstance()` pozamieniać na korzystanie z danych dostarczonych przez graczy. `change_diff()` można wywołać na graczu komputerowym przed grą, nie jest potrzebne zmienianie trudności w czasie gry (nadto nie używamy skrótów: diff-erence?)
6. [Co to za kolory](https://github.com/Bartosz007/cztery-w-rzedzie/blob/91fcb3779fbba129f1024442cd2b2d4ddeb2f60b/game_mechanics.py#L55) i czemu nie są w stałych?
7. [Tutaj](https://github.com/Bartosz007/cztery-w-rzedzie/blob/91fcb3779fbba129f1024442cd2b2d4ddeb2f60b/game_mechanics.py#L27) czy nie lepiej trzymać graczy w liście 2-elementowej i przemianować `round` na `current_player`?
8. [Brakuje `t`](https://github.com/Bartosz007/cztery-w-rzedzie/blob/91fcb3779fbba129f1024442cd2b2d4ddeb2f60b/game_mechanics.py#L18).
9. [Czemu `set_geometry()` jest oderwane od `__init__()`](https://github.com/Bartosz007/cztery-w-rzedzie/blob/91fcb3779fbba129f1024442cd2b2d4ddeb2f60b/game_mechanics.py#L33) (4. rozdział)?
10. Może być [`from tkinter import messagebox`](https://github.com/Bartosz007/cztery-w-rzedzie/blob/91fcb3779fbba129f1024442cd2b2d4ddeb2f60b/game_frame.py#L5).
11. Co to za [5](https://github.com/Bartosz007/cztery-w-rzedzie/blob/91fcb3779fbba129f1024442cd2b2d4ddeb2f60b/game_frame.py#L40)?
12. Lepiej `constants.py`.
13. [To i następne](https://github.com/Bartosz007/cztery-w-rzedzie/blob/91fcb3779fbba129f1024442cd2b2d4ddeb2f60b/utils/players_utils.py#L98) widzę wszędzie, w testach też. Wyjąć do 2 funkcji.

**Comment by Bartosz007** [comment]
Popoprawiałem wszystkie wymienione wyżej podpunkty. Część z nich wynikało z mojego niedopatrzenia.
Głównie zmiany dotyczyły się punktu 5 i 7. Zmieniłem dwie zmienne graczy na tablicę.  Sama gra zaczyna się w momencie, kiedy gracz(musi to być człowiek) naciśnie przycisk nad kolumną. Do tej pory można zmieniać typ gracza i jego poziom trudności, dlatego ta funkcja od zmiany poziomu trudności dalej tam jest. 
9. To wynikało z tego, że obiekt GameMechanics tworzył się wcześniej niż plansza i trzeba było dostarczyć potem jeszcze obiekty do rysowania i wyświetlania komunikatów.
11. Ta 5 to początkowa pozycja na jaką ma spaść moneta. Czyli 5 to sam dół planszy. Ma ona  7 elementów odpowiadających każdej kolumnie. Dekrementują się one po każdorazowym wybraniu kolumny przez gracza.

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany. Jest nieźle.

1. [7](https://github.com/Bartosz007/cztery-w-rzedzie/blob/52ee37b069a22d25895039e23e3ba13727f3a92b/game_frame.py#L116) nazwać.
2. [Lepiej importować moduły](https://github.com/Bartosz007/cztery-w-rzedzie/blob/52ee37b069a22d25895039e23e3ba13727f3a92b/game_frame.py#L10) (2. rozdział).
3. [`from utils import players_utils`](https://github.com/Bartosz007/cztery-w-rzedzie/blob/52ee37b069a22d25895039e23e3ba13727f3a92b/players/computer_player.py#L4) (bez `as pu`).
4. W punkcie 11. chodziło mi nie tyle o uzyskanie wyjaśnienia, co o zamianę 5 na nazwaną stałą (jak sądzę, coś w rodzaju wysokości planszy - 1).

**Comment by Bartosz007** [comment]
Popoprawiałem wszystko. Mam nadzieję, że dobrze.

**Comment by MarcinCiura** [comment]
Jest dobrze. Zostały Panu do poprawienia głupotki i będzie po wszystkim

1. Zamiast [`ROWS` i `COLS`](https://github.com/Bartosz007/cztery-w-rzedzie/blob/b5641dc6787336099c0b257a171e6bc622805d60/utils/constants.py#L30) wolałbym `NUM_ROWS` i `NUM_COLUMNS`.
2. [Lepiej dwa osobne wiersze](https://github.com/Bartosz007/cztery-w-rzedzie/blob/b5641dc6787336099c0b257a171e6bc622805d60/players/computer_player.py#L4).
3. [Co to za `f`](https://github.com/Bartosz007/cztery-w-rzedzie/blob/b5641dc6787336099c0b257a171e6bc622805d60/players/computer_player.py#L23)?

**Comment by Bartosz007** [comment]
Poprawione

**Comment by MarcinCiura** [comment]
LGTM. Gratuluję pracowitości, jest Pan szósty.

**Comment by Bartosz007** [comment]
Dziękuję za wszystkie uwagi.
